%define _empty_manifest_terminate_build 0

%define libname %mklibname libre-graph-api-cpp-qt-client
%define devname %mklibname -d libre-graph-api-cpp-qt-client

%define api 1

Name:           libre-graph-api-cpp-qt-client
Version:        1.0.4
Release:        1
Summary:        Libre Graph Cloud Collaboration API
License:        Apache-2.0
URL:            https://owncloud.dev/libre-graph-api/
Source:         https://github.com/owncloud/libre-graph-api-cpp-qt-client/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  cmake
BuildRequires:  qt5-qtbase-devel
BuildRequires:  pkgconfig(zlib)

%description
Libre Graph API

API version: v1.0.1
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

%package -n %{libname}
Summary:        Shared library for %{name}
Provides:       libre-graph-api-cpp-qt-client

%description -n %{libname}
Library for libre-graph-api-cpp-qt-client

%package -n %{devname}
Summary:        Development files for %{name}
Requires:	%{libname} = %{version}-%{release}

%description -n %{devname}
Development files for libre-graph-api-cpp-qt-client
 
%prep
%autosetup -p1

%build
pushd client
%cmake
%make_build

%install
pushd client
%make_install -C build

%files -n %{libname}
%{_libdir}/libLibreGraphAPI.so.%{api}*

%files -n %{devname}
%{_includedir}/OpenAPI/
%{_libdir}/cmake/LibreGraphAPI/
%{_libdir}/libLibreGraphAPI.so
